platform :ios, '8.0'
target “voiceDemo_hyc” do use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'ReactiveObjC', '~> 2.1.0'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'CocoaAsyncSocket', '~> 7.5.1'
pod 'MBProgressHUD', '~> 1.0.0'
end